version: '3.8'

services:
  sxw-codex:
    image: sxw-codex:latest
    container_name: sxw_codex_manager
    ports:
      - "8001:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data-sxw:/app/data

  wenfxl-codex:
    image: wenfxl-codex:latest
    container_name: wenfxl_codex_manager
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data-wenfxl:/app/data
